export const ACCESS_TOKEN_SIG_COOKIE = 'tsa'
export const ACCESS_TOKEN_LIFE_TIME = 900000 // 15 min
export const REFRESH_TOKEN_LIFE_TIME = 6.307e10 // 2 year
export const REFRESH_TOKEN_SIG_COOKIE = 'tsr'
export const DEFAULT_MEM_CACHE_TIME = 30 // 30s
export const MAX_RETRY_GET_TOKEN_NUMBER = 3
export const MAX_RETRY_EXCHANGE_CODE = 3
export const AUTH_PAYLOAD_HEADER_NAME = 'au-payload'
export const GGJ_REDIRECT_CODE = 456
