export { SurfaceLayout, nsTranSurfaceLayout } from './surface/SurfaceLayout'
export { SurfaceDetailLayout , nsTranSurfaceDetailLayout} from './surface/SurfaceDetailLayout'
export { SurfaceSearchLayout , nsTranSurfaceSearchLayout} from './surface/SurfaceSearchLayout'
export { SurfacePaymentsLayout , nsTranSurfacePaymentsLayout} from './surface/SurfacePaymentsLayout'
export { SurfaceUsersLayout , nsTranSurfaceUserLayout} from './surface/SurfaceUsersLayout'
export { MypageLayout, nsTranMypageLayout } from './mypage/MypageLayout'
export { MypageDetailLayout, nsTranMypageDetailLayout } from './mypage/MypageDetailLayout'
export { MypageTransactionLayout, nsMypageTransactionLayout } from './mypage/MypageTransactionLayout'
export { MypageTransactionDetailLayout, nsMypageTransactionDetailLayout } from './mypage/MypageTransactionDetailLayout'
export { InquiryLayout, nsTranInquiryLayout } from './inquiry/InquiryLayout'
export {SurfaceTermLayout, nsTranSurfaceTermLayout} from './surface/SurfaceTermLayout'
